MQTT Implementation and HiveMQ connection
OpenFogStack/matterHub pull request #40
Opened 2022-06-10 23:20 UTC by Ti-ger

# Pull Request Checklist

## Author

- [ ] Built code and tested locally
- [ ] Removed any TODOs, etc.
- [ ] Metioned the issue this PR closes
- [ ] Good description of what the PR does written

## Reviewer

- [ ] Built and tested code locally
- [ ] Fully understood the PR
- [ ] All open conversations resolved

2022-06-10 23:26 UTC, Ti-ger commented
Adds MQTT Support by using the ESP-IDF MQTT Client. 
Also implements the CLI and some logic to delay commands when the Connection HiveMQ is disrupted.
TODOs:
- Check if we really want to use this tcp client and this event-loop. 
My guess is: this is exactly what Matter uses under the hood, but we should verify this.

- Create a shared HiveMQ Account
- Store credentials in a way not everybody can see them...

2022-06-17 15:09 UTC, vringar commented
Just curious, why is this not implemented via another git submodule?
This seems to be a copy of a whole repository including Travis and Gitlab CI config?

2022-06-23 09:47 UTC, Ti-ger commented
> 

You are right, this is a leftover. I thought we may have to replace all the socket calls with "Matter Socket" calls and so on. 
Luckily this was not necessary. I will remove all the files, thanks for the hint!

2022-06-24 13:47 UTC, bowski23 commented
Don't worry about the force-pushed changes. This was done to get rid of the secrets stored in past commits.

2022-06-27 18:57 UTC, vringar requested changes
This is mostly a first pass. I need to look through this more thoroughly.

2022-06-27 18:57 UTC, vringar commented on src/main/CMakeLists.txt
> +                      "${CMAKE_SOURCE_DIR}/third_party/connectedhomeip/zzz_generated/app-common/app-common/zap-generated/ids"
Did I introduce this artifact or is this deliberate?

2022-06-27 18:57 UTC, vringar commented on src/main/Kconfig.projbuild
> +endmenu
Should we mention this in the readme?

2022-06-27 18:57 UTC, vringar commented on src/main/MQTTManager.cpp
> +#include "MQTTManager.h"
License header missing

2022-06-27 18:57 UTC, vringar commented on src/main/MQTTManager.cpp
> +//
I don't understand this comment

2022-06-27 18:57 UTC, vringar commented on src/main/include/MQTTManager.h
> +#pragma once
License header missing

2022-06-27 18:57 UTC, vringar commented on src/main/include/Subscription.h
>  #pragma once
License header missing

2022-06-27 18:57 UTC, vringar commented on src/main/include/Subscription.h
> +        // TODO: What we want to use:
Is this todo for this PR or for followup?

2022-06-30 10:05 UTC, Ti-ger commented on src/main/MQTTManager.cpp
> +//
Remainder of the Orignal source code. I am also not completely sure about its content. 
However the author itself uses the function for more  than just testing :see_no_evil:

2022-06-30 10:06 UTC, Ti-ger commented on src/main/include/Subscription.h
> +        // TODO: What we want to use:
This is definitely a follow up. We could use this for the ZAP-Tool integration

2022-06-30 10:12 UTC, Ti-ger commented on src/main/CMakeLists.txt
> +                      "${CMAKE_SOURCE_DIR}/third_party/connectedhomeip/zzz_generated/app-common/app-common/zap-generated/ids"
I introduced this for the "Attribute.h"-header, but it is currently not used. 
I removed it again ;)

2022-07-04 16:41 UTC, closed without merging