Feat/discover
OpenFogStack/matterHub pull request #58
Opened 2022-07-01 15:32 UTC by bowski23

# Pull Request Checklist

## Author

- [ ] Built code and tested locally
- [ ] Removed any TODOs, etc.
- [ ] Metioned the issue this PR closes
- [ ] Good description of what the PR does written

## Reviewer

- [ ] Built and tested code locally
- [ ] Fully understood the PR
- [ ] All open conversations resolved

2022-07-03 15:24 UTC, vringar requested changes
Sorry that this contains too many nitpicks.

2022-07-03 15:24 UTC, vringar commented on src/main/DiscoverCommands.cpp
> +}
```suggestion
    Platform::Delete(data);
}
```

2022-07-03 15:24 UTC, vringar commented on src/main/include/ConnectionHelper.h
> +#pragma once
Add a license header please.
Maybe we should make this part of clang-format.

2022-07-03 15:24 UTC, vringar commented on src/main/include/DiscoverCommands.h
> +#include "BaseCommand.h"
License header

2022-07-03 15:24 UTC, vringar commented on src/main/include/Subscription.h
> +        mDevice(device), mMinInterval(1), mMaxInterval(10), mCallback(callback)
Nice overload!

2022-07-03 15:24 UTC, vringar commented on src/main/include/Subscription.h
> +typedef void (*SubscriptionCallback)(const chip::app::ConcreteDataAttributePath &, chip::TLV::TLVReader *);
I prefer using over typedef, but that can also be fixed through tooling later.

2022-07-03 15:24 UTC, vringar commented on src/main/include/Subscription.h
> +        if (type == chip::TLV::TLVType::kTLVType_Boolean)
Okay, so in the future we'd want to call into generated code here that contains a giant switch based on types, right?

2022-07-03 16:35 UTC, bowski23 commented on src/main/ConnectionHelper.cpp
> +namespace {
I assumed it was intentional, as it was defined this way in the other project files as well.

2022-07-08 09:10 UTC, vringar commented on scripts/demo/config
> +set PASSWORD "Spr33@u3ll13355"
This shouldn't be committed here.

2022-07-08 11:25 UTC, bowski23 commented on scripts/demo/config
> +set PASSWORD "Spr33@u3ll13355"
i know i added this line to the readme, it was done by mistake because i had to take it out from the tracking when you commited your info lmao

2022-07-08 12:40 UTC, bowski23 commented on scripts/demo/config
> +set PASSWORD "Spr33@u3ll13355"
I think it should be alright now. When there are different versions of a file between branches and have one of them changed you are just not allowed to ignore your local changes while switching branches.

2022-08-19 07:13 UTC, closed without merging