Uploaded the design decisions
OpenFogStack/matterHub pull request #85
Opened 2022-08-21 19:42 UTC by Emirhan-Atabay

I forgot to upload the design decisions - sorry!

#64 #56
# Pull Request Checklist

## Author

- [x] Built code and tested locally
- [x] Removed any TODOs, etc.
- [x] Metioned the issue this PR closes
- [x] Good description of what the PR does written

## Reviewer

- [ ] Built and tested code locally
- [ ] Fully understood the PR
- [ ] All open conversations resolved

2022-08-21 20:06 UTC, vringar requested changes

2022-08-21 20:06 UTC, vringar commented on docs/design_decisions_paho.md
> +|<b>Benefits and risks</b>|+ JAVA|+ Python<br>+ generic MQTT support|
What does python have to do with any of this?
We were considering two different Java libraries? Right?

2022-08-21 20:06 UTC, vringar commented on docs/design_decisions_server.md
> +|The MatterHub can interact with the Enddevice once the program is implemented.|
Don't you mean that the IOT things cloud can interact with the end device? Because the mattterhub and the enddevice are on the same side of this discussing.

2022-08-21 20:06 UTC, vringar commented
You can also just merge these and then fix 'em up for the report, but these two things confused me.

2022-08-21 20:52 UTC, Emirhan-Atabay commented on docs/design_decisions_server.md
> +|The MatterHub can interact with the Enddevice once the program is implemented.|
yeah you are right, I changed that

2022-08-21 20:52 UTC, Emirhan-Atabay commented on docs/design_decisions_paho.md
> +|<b>Benefits and risks</b>|+ JAVA|+ Python<br>+ generic MQTT support|
Oh my fault, I thought Paho was Python only. I will change that too

2022-08-22 04:25 UTC, Emirhan-Atabay commented
@vringar I changed the Paho Design Decision. Now it's ready to merge, what do you think?

2022-08-22 07:35 UTC, vringar approved these changes

2022-08-22 07:36 UTC, merged